// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI novamente.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI novamente.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI novamente.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0SlnlHPDaoJutqIuAfTsSJJH22a2KetM',
    appId: '1:317771367093:web:906e54159c7940a13c74fc',
    messagingSenderId: '317771367093',
    projectId: 'petkeepr-ad816',
    authDomain: 'petkeepr-ad816.firebaseapp.com',
    databaseURL: 'https://petkeepr-ad816-default-rtdb.firebaseio.com',
    storageBucket: 'petkeepr-ad816.appspot.com',
    measurementId: 'G-BVHQQSM52S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwaTrUfTnp0Y6jmLRxq_4Ahlwt6JrCR0s',
    appId: '1:317771367093:android:80489e1b0eb558563c74fc',
    messagingSenderId: '317771367093',
    projectId: 'petkeepr-ad816',
    databaseURL: 'https://petkeepr-ad816-default-rtdb.firebaseio.com',
    storageBucket: 'petkeepr-ad816.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYDOKEqrie6yrny8bd2b6Hu8cJds71LOM',
    appId: '1:317771367093:ios:71deef6598d72ab73c74fc',
    messagingSenderId: '317771367093',
    projectId: 'petkeepr-ad816',
    databaseURL: 'https://petkeepr-ad816-default-rtdb.firebaseio.com',
    storageBucket: 'petkeepr-ad816.appspot.com',
    iosBundleId: 'com.example.petkeeperLite',
  );
}
